### ISSUE TITLE
Status of this repo/gem

### ISSUE THREAD

**Issue by jasnow** [Intrepidd/rails-footnotes#162]
What is the status of this repo/gem? Is it still being maintained? Should it be transferred to someone else's fork?

**Comment by Intrepidd** [comment]
Hi,

Unfortunately I'm not maintaining this repo anymore. I'd gladly let someone else take over but I don't have the rights to do so, you'll need to ask @josevalim directly.

**Comment by jasnow** [comment]
@Intrepidd - Thanks for responding

**Comment by josevalim** [comment]
@Intrepidd is it ok if I transfer the repo to you? Or maybe we should archive the repo?

**Comment by Intrepidd** [comment]
I'd be ok to have it transfered to me ! I'll also need full rights on rubygems so I can add other maintainers

**Comment by josevalim** [comment]
It is saying "Intrepidd/rails-footnotes already exists". Is it possible for you to delete that fork?

**Comment by Intrepidd** [comment]
Done !

**Comment by josevalim** [comment]
@Intrepidd done, thank you for maintaining the repo all of this time, sorry that I didn't transfer it sooner! :heart:

**Comment by kbrock** [comment]
Thanks for transferring it guys.
And @josevalim, even after you have passed this gem on, you remain super responsive. (for this and other gems). Thank you for that

**Comment by jasnow** [comment]
FYI: Can not use this version of the gem without PR #157

**Comment by jasnow** [comment]
Appears this ticket is not going to be worked so I'm going to close it and use the other person's versions of this gem.

**Comment by kbrock** [comment]
@jasnow could you share a link to the repo that you will use. so future people who find this issue may gain that knowledge? thnx

**Comment by jasnow** [comment]
https://github.com/I-de-ya/rails-footnotes
